### ISSUE TITLE
selector.insertAfter(selector, parser.attribute(attribute: 'xxx')); will undefined!

### ISSUE THREAD

**Issue by foreverzmy** [postcss/postcss-selector-parser#125]
selector.insertAfter(selector, parser.attribute(attribute: 'xxx'));!
the attribute change to _attribute, make the css selector become undefined.

os: win10
version: 3.1.1

**Comment by pmdartus** [comment]
Hi @foreverzmy, I am not sure to understand the issue here. 
Can you share a minimal snippet of code with the issue that you are facing?

**Comment by orblazer** [comment]
Hello i continue this issue because i have the same bug.

The code (from [Fuse-Box > PostCSSPlugin#L23](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/vue/PostCSSPlugins.ts#L23)) :
```ts
node.selector = selectorParser(function (selectors) {
  selectors.each(function (selector) {
    let node = null
    selector.each(function (n) {
      // ">>>" combinator
      if (n.type === 'combinator' && n.value === '>>>') {
        n.value = ' '
        n.spaces.before = n.spaces.after = ''
        return false
      }
      // /deep/ alias for >>>, since >>> doesn't work in SASS
      if (n.type === 'tag' && n.value === '/deep/') {
        let next = n.next()
        if (next.type === 'combinator' && next.value === ' ') {
          next.remove()
        }
        n.remove()
        return false
      }
      if (n.type !== 'pseudo' && n.type !== 'combinator') {
        node = n
      }
    })
    selector.insertAfter(node, selectorParser.attribute({
      attribute: opts.id
    }))
  })
}).process(node.selector).result
```

This code is based from [VueLoader > scope-id.js#L20](https://github.com/vuejs/vue-loader/blob/master/lib/style-compiler/plugins/scope-id.js#L20).

This is produce `undefined` selector.
Eg: `.error { ... }` result `undefined { ... }` but we wait `.error[...] { ... }`.

Thanks.

**Comment by orblazer** [comment]
Ok i am stupid i have found the problem.

My implementation is wrong.
i have `.process(node.selector).result` but the correct is `.process(node.selector).then((result) => ...)`

**Comment by chriseppstein** [comment]
Yeah, this bit me too. 

Fun fact: with the new typescript definitions, if you have a typescript project, this sort of issue is immediately obvious ^_^
