### ISSUE TITLE
Roadmap for version 2.

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#24]
* Consistency with PostCSS 5; `eachTag` -> `walkTags`, `node.removeSelf()` -> `node.remove()`.

Other breaking suggestions welcome.

**Comment by jonathantneal** [comment]
- Processor extends Root

This would let us put the selector before the selector’s transform, which works better in my head, at least. The breaking change would be that this means the processor takes a selector string instead of a transform function.

- walk methods ('each', 'walk', 'walkXs') accept `([filter,] callback)`

Like PostCSS, this save us the trouble of adding the additional filter in our callback.

- walk methods returns the processor

This would let us chain walkers and append a toString right at the end.

```js
parser('p &, & p').each(function (selector) {
  selector.walkTags('&', function (tag) {
    tag.value = 'section';
  });
}).toString(); // returns 'p section, section p'
```

**Comment by jeddy3** [comment]
* Parse for the _nesting selector (&)_

Ref: https://github.com/stylelint/stylelint/issues/499 .

**Comment by ben-eb** [comment]
I've had a thought, now I'm not really convinced that string filters are a good API design for this parser. Some selector types are just single strings (like `universal`) and so a filter is unnecessary for these purposes, plus I'd prefer that people use the `walk` method anyway;

```js
var parser = require('postcss-selector-parser');
var transform = function (selectors) {
    selectors.walk(function (selector) {
        if (selector.type !== 'nesting') {
            return;
        }
        selector.value = 'section';
    });
};

var transformed = parser(transform).process('p &, & p').result;
```
