### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss-selector-parser#26]
Fascinating project, first off. Thanks for making your work available. I do have a few questions that I couldn't find the answers to in the repo:

- postcss-selector-parser's name and parent org on Github suggest that it's a project for postcss. Is this project being integrated with postcss proper, or is there a manual means to integrate the project with postcss on the consumers end, in code?

- If not, is the plan for postcss-selector-parser to be integrated in the future?

- Can postcss-selector-parser be extended to support preprocessor features (like LESS, etc)?

**Comment by ai** [comment]
@shellscape `postcss-selector-parser` is a too to parse selectors in PostCSS plugins. Because PostCSS do not parse seectors deeply, it return just a strings. But you can use `postcss-selector-parser` to parse selector in any tool, not in PostCSS plugin (it accepts string and return AST). Yes, threre is a plan to add it to PostCSS, but it will not be soon.

**Comment by shellscape** [comment]
@ai thanks for the quick answers, much appreciated.

**Comment by shellscape** [comment]
fwiw I've started on a less syntax built upon the postcss-scss syntax, and modified. https://github.com/gilt/postcss-less very pleased with how easy is it to use these patterns. would welcome any feedback as this is my first foray into the project. /cc @ai
